sudo: required
services:
  - docker

before_install:
  - docker build -t rodvind/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rodvind/react-test npm test

after_success:
  - docker build -t rodvind/fibona-client ./client
  - docker build -t rodvind/fibona-nginx ./nginx
  - docker build -t rodvind/fibona-server ./server
  - docker build -t rodvind/fibona-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push rodvind/fibona-client
  - docker push rodvind/fibona-nginx
  - docker push rodvind/fibona-server
  - docker push rodvind/fibona-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'fibona'
  env: 'Fibona-env'
  bucket_name: 'elasticbeanstalk-us-east-1-387934445668'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY